### ISSUE TITLE
Missing config file

### ISSUE THREAD

**Issue by brunoboehmm** [bf777/MesoNet#8] opened 2021-12-02 10:46 UTC
Hi,
I've tried to use the GUI on my conda deeplabcut environment. It launches correctly, I can select my input and output folders, but as soon as I try using the "Atlas to Brain" option, I get the following error message, even though I did change the paths on the config.yaml file to match my computer's. Do you know where this comes from, should I modify an existing file, or is something missing from my environment ?
Thanks in advance
![Error_config](https://user-images.githubusercontent.com/88535509/144407121-65ca08d5-cedc-4716-a646-256f34c6da63.JPG)

**Comment by bf777** [comment] 2021-12-05 19:12
Hi @brunoboehmm, thanks for reaching out! If you're using the default config file, it should not be necessary to change the filepath. It looks like your input images are inside your MesoNet git repository folder (`MesoNet-master/mesonet`) - this can potentially cause issues with filepaths. Could you try placing your input image folder outside of the MesoNet git repository (i.e. outside of `MesoNet-master`) and try again? Thanks!

**Comment by brunoboehmm** [comment] 2021-12-06 08:39
Hi,
Thank you for your help! I tried this, but I still have the exact same error message...

**Comment by bf777** [comment] 2021-12-06 08:51
Hi @brunoboehmm, could you try putting the DeepLabCut model folder (if you're using the default from OSF, it's `atlas-DongshengXiao-2020-08-03` into a subfolder called `dlc` within the `mesonet` folder of the git repository? I realize the instructions in the wiki said to put it into the `models` folder directly; I may need to correct that. You can also do this process automatically by running `get_default_models.sh` within the `mesonet` folder. 

If that doesn't help, I recommend you run `test.py` within the `tests` folder of the repository to verify that the code works properly on a sample dataset.

I hope this helps!

**Comment by brunoboehmm** [comment] 2021-12-06 12:13
The test.py actually runs and is able to locate the landmarks (I get the "Landmark prediction complete!" display when I run it) but as soon as I select the Atlas to Brain or Brain to Atlas function on the GUI, I get the config error message.

**Comment by bf777** [comment] 2021-12-08 19:10
I should be able to test the GUI today or tomorrow to see what is happening. In the meantime, if you have placed the default DeepLabCut model in the default location, you should not need to change the filepath to the model in the GUI - see if that works. Additionally, in the meantime the following Python code should replicate the atlas-to-brain method in the GUI:

```
import mesonet

config_file_atlas_brain = mesonet.config_project(input_file, output_file_atlas_brain, 'test',                                   atlas_to_brain_align=True, use_voxelmorph=False,               use_unet=True, use_dlc=True, sensory_match=False, mat_save=False, config=dlc_config, model=model)

# Identify outer edges of the cortex
  mesonet.predict_regions(config_file_atlas_brain)

# Identify and use cortical landmarks to align the atlas to the brain
    mesonet.predict_dlc(config_file_atlas_brain)
```

The first two arguments are your input and output folders, `dlc_config` is the path to your DeepLabCut config file, and `model` is the name of the default .hdf5 U-Net model that you selected in the list box on the right side of the GUI.

I hope this works for now! Thanks for your patience.

**Comment by bf777** [comment] 2021-12-10 04:42
Hi @brunoboehmm, I believe I have resolved the issue. The behaviour of opencv's `VideoWriter` changed and I had to update the default codec used on Windows for writing the DeepLabCut video for landmark estimation (in df7323f4c8db10b1793d12571c0e1afe83a52f37). Please pull the latest code and install it; it should hopefully work then. I think that the DeepLabCut model folder location should also not matter with this change, so long as you select the config file in the GUI. Please let me know if you are still experiencing issues, and sorry for any inconvenience!

**Comment by brunoboehmm** [comment] 2021-12-14 12:31
Hi,
Thanks a lot for all your help, I'm sorry I haven't answered earlier, I haven't had the time to test the GUI again since Friday. I uninstalled everything, reinstalled the latest version of MesoNet, selected the config file (the one from the DLC folder), but still have the same error message...

**Comment by bf777** [comment] 2021-12-15 03:23
No problem! I've just tested it again and it works for me on Windows 10 when the DLC folder (e.g. `atlas-DongshengXiao-2020-08-03`) is placed outside of the MesoNet repo and the config file inside this folder is selected. Try copying and pasting the model folder outside of your MesoNet folder, then selecting the config file in that folder when using the MesoNet GUI..

I hope this helps!

**Comment by brunoboehmm** [comment] 2021-12-17 10:31
Thank you for your quick answer and your help, unfortunately, even with this I still get the same error message. Just to make sure though, when you talk about the model folder, you talk about the atlas-DongshengXiao-2020-08-03, not the actual "models" folder containing the U-Net models? Because this folder has to stay in my MesoNet repo (otherwise the GUI can't find the model files...). Also, I have to manually change the "MesoNet git repo folder" path on the GUI as the default one is now weird (C:\$Recycle.Bin\S-1-5-21-2549886845-264585227-397852783-218182\$R3TOLBK\mesonet) since I deleted and reinstalled the MesoNet files. But here if I simply put the path of the latest version of the main folder (MesoNet) it should work, right?
Anyway thanks for you help! Hope you still have an idea for this...

**Comment by bf777** [comment] 2021-12-17 18:17
No problem! By model folder I mean `atlas-DongshengXiao-2020-08-03` - just move this folder outside of the git repo and use it from there, and don't move the `models` folder (the U-Net .hdf5 models can stay where they are).

Regarding the git repo path - make sure to fully delete the previous MesoNet folder in your recycle bin as it may be trying to use that folder instead. Although it should work if you manually change this git repo path, it's best to delete the old one just to be safe.

Hope this helps!

**Comment by brunoboehmm** [comment] 2021-12-20 10:57
Thanks for the tips, this is indeed exactly what I did, but I just wanted to make sure. I also emptied the whole recycle bin, so the automatic paths now work correctly, but still I get the config error message.

**Comment by bf777** [comment] 2021-12-20 23:35
Thanks for letting me know! If you've tried using the DeepLabCut model folder outside of the MesoNet repo, while not changing the automatic path in the DeepLabCut config file within this model folder, and it's still not working, I would recommend trying the command-line based method for now (the functionality will be the same; be sure to replace `input_file`, `output_file`, `config`, and `model` with the appropriate filepaths):
```
import mesonet

input_file = 'path/to/input/folder'

output_file =' path/to/output/folder'

config = 'path/to/dlc/config/file'

model = 'name of hdf5 model file for U-Net'

config_file = mesonet.config_project(input_file, output_file, 'test', atlas_to_brain_align=True, use_voxelmorph=False, use_unet=True, use_dlc=True, sensory_match=False, mat_save=False, config=dlc_config, model=model)

# Identify outer edges of the cortex
mesonet.predict_regions(config_file)

# Identify and use cortical landmarks to align the atlas to the brain
mesonet.predict_dlc(config_file)
```
I will continue to look into this issue on Windows. A few additional things I would recommend trying are:
1. Ensuring that the filepath under `videos` in the `atlas-DongshengXiao-2020-08-03` config file looks similar to the first, automatically set filepath (this second filepath is not always set automatically; it should point to a .avi video within `atlas-DongshengXiao-2020-08-03`).
2. Deleting other versions of the folder `atlas-DongshengXiao-2020-08-03` on your computer (including the one in the git repo).
3. Running the GUI using ipython (this the main environment in which it was tested).
4. Using MesoNet in a virtual environment (e.g. Anaconda or Miniconda), if you haven't already (in case the issue results from interfering software versions - which it shouldn't unless you have more than one instance of DeepLabCut on your computer, but just in case).
5. If you have more than one drive connected, checking that your model folder and MesoNet code are all installed on drive C: (we don't yet support other drive letters on Windows unless you manually specify the path to the git repository).

Thank you for your patience!

**Comment by bf777** [comment] 2022-02-14 22:17
Closing issue due to inactivity.

**Comment by scottkil** [comment] 2023-02-20 20:53
Hi,

I ran into the same problem as @brunoboehmm. I've tried moving [atlas-DongshengXiao-2020-08-03] outside the MesoNet folder and setting the path to the video file correctly, but it's still not working. I'm still getting that 'config file is not found' error. 

While troubleshooting, I ran test.py and got the error below. Also, based on reading the other issue threads, I suspect you might ask for the OpenCV version so I've included that here too. 

<pre><font color="#26A269">In [</font><font color="#33DA7A"><b>18</b></font><font color="#26A269">]: </font><font color="#008700">print</font>(cv2. __version__)
4.7.0
</pre>


<pre><font color="#26A269">In [</font><font color="#33DA7A"><b>13</b></font><font color="#26A269">]: </font>%run test.py
Creation of the directory /home/scott/Documents/MesoNet/mesonet/../tests/results/mesonet_output_atlas_brain failed
Creation of the directory /home/scott/Documents/MesoNet/mesonet/../tests/results/mesonet_output_brain_atlas failed
Creation of the directory /home/scott/Documents/MesoNet/mesonet/../tests/results/mesonet_output_sensory failed
Creation of the directory /home/scott/Documents/MesoNet/mesonet/../tests/results/mesonet_output_MBFM_U_Net failed
Creation of the directory /home/scott/Documents/MesoNet/mesonet/../tests/results/mesonet_output_voxelmorph failed
/home/scott/Documents/MesoNet/mesonet/models/DongshengXiao_brain_bundary.hdf5
1. Atlas-to-brain warp with U-Net and DeepLabCut
/home/scott/Documents/MesoNet/mesonet
/home/scott/Documents/MesoNet/mesonet/models/DongshengXiao_brain_bundary.hdf5
2023-02-20 15:28:58.933354: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library &apos;libcufft.so.10&apos;; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/scott/anaconda3/envs/DLC/lib/python3.8/site-packages/cv2/../../lib64:
2023-02-20 15:28:59.026245: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library &apos;libcusparse.so.11&apos;; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/scott/anaconda3/envs/DLC/lib/python3.8/site-packages/cv2/../../lib64:
2023-02-20 15:28:59.026459: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-02-20 15:29:00.047118: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-20 15:29:00.084229: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
/home/scott/Documents/MesoNet/mesonet/../tests/sample_data/pipeline1_2
/home/scott/anaconda3/envs/DLC/lib/python3.8/site-packages/mesonet-1.0.5.3-py3.8.egg/mesonet/predict_regions.py:93: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
/home/scott/anaconda3/envs/DLC/lib/python3.8/site-packages/keras/engine/training_v1.py:2356: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
Output cortex masks can be found in `results/mesonet_output_atlas_brain/output_mask`
2
/home/scott/Documents/MesoNet/mesonet/../tests/sample_data/pipeline1_2/0.png
/home/scott/Documents/MesoNet/mesonet/../tests/sample_data/pipeline1_2/1.png
OpenCV: FFMPEG: tag 0x4745504d/&apos;MPEG&apos; is not supported with codec id 2 and format &apos;mp4 / MP4 (MPEG-4 Part 14)&apos;
OpenCV: FFMPEG: fallback to use tag 0x7634706d/&apos;mp4v&apos;
<font color="#C01C28">---------------------------------------------------------------------------</font>
<font color="#C01C28">FileNotFoundError</font>                         Traceback (most recent call last)
File <font color="#26A269">~/Documents/MesoNet/tests/test.py:97</font>
<font color="#26A269"><b>     94</b></font> <font color="#008700">print</font>(<font color="#AF0000">&apos;Output cortex masks can be found in `results/mesonet_output_atlas_brain/output_mask`&apos;</font>)
<font color="#26A269"><b>     96</b></font> <font color="#5F8787"><i># Identify and use cortical landmarks to align the atlas to the brain</i></font>
<font color="#26A269">---&gt; 97</font> <span style="background-color:#A2734C">mesonet</span><span style="background-color:#A2734C"><font color="#626262">.</font></span><span style="background-color:#A2734C">predict_dlc(config_file_atlas_brain)</span>
<font color="#26A269"><b>     99</b></font> <font color="#008700">print</font>(<font color="#AF0000">&apos;Output aligned brain images and atlases can be found in `results/mesonet_output_atlas_brain/output_overlay`&apos;</font>)
<font color="#26A269"><b>    101</b></font> <font color="#5F8787"><i>## 2. Brain to atlas</i></font>
<font color="#26A269"><b>    102</b></font> <font color="#5F8787"><i># Brain-to-atlas warp with DeepLabCut</i></font>

File <font color="#26A269">~/anaconda3/envs/DLC/lib/python3.8/site-packages/mesonet-1.0.5.3-py3.8.egg/mesonet/dlc_predict.py:373</font>, in <font color="#2AA1B3">predict_dlc</font><font color="#12488B">(config_file)</font>
<font color="#26A269"><b>    371</b></font> flow_path <font color="#626262">=</font> cfg[<font color="#AF0000">&quot;flow_path&quot;</font>]
<font color="#26A269"><b>    372</b></font> coords_input_file <font color="#626262">=</font> cfg[<font color="#AF0000">&quot;coords_input_file&quot;</font>]
<font color="#26A269">--&gt; 373</font> <span style="background-color:#A2734C">DLCPredict(</span>
<font color="#26A269"><b>    374</b></font> <span style="background-color:#A2734C">    config,</span>
<font color="#26A269"><b>    375</b></font> <span style="background-color:#A2734C">    input_file,</span>
<font color="#26A269"><b>    376</b></font> <span style="background-color:#A2734C">    output,</span>
<font color="#26A269"><b>    377</b></font> <span style="background-color:#A2734C">    atlas,</span>
<font color="#26A269"><b>    378</b></font> <span style="background-color:#A2734C">    sensory_match,</span>
<font color="#26A269"><b>    379</b></font> <span style="background-color:#A2734C">    sensory_path,</span>
<font color="#26A269"><b>    380</b></font> <span style="background-color:#A2734C">    mat_save,</span>
<font color="#26A269"><b>    381</b></font> <span style="background-color:#A2734C">    threshold,</span>
<font color="#26A269"><b>    382</b></font> <span style="background-color:#A2734C">    git_repo_base,</span>
<font color="#26A269"><b>    383</b></font> <span style="background-color:#A2734C">    region_labels,</span>
<font color="#26A269"><b>    384</b></font> <span style="background-color:#A2734C">    landmark_arr,</span>
<font color="#26A269"><b>    385</b></font> <span style="background-color:#A2734C">    use_unet,</span>
<font color="#26A269"><b>    386</b></font> <span style="background-color:#A2734C">    use_dlc,</span>
<font color="#26A269"><b>    387</b></font> <span style="background-color:#A2734C">    atlas_to_brain_align,</span>
<font color="#26A269"><b>    388</b></font> <span style="background-color:#A2734C">    model,</span>
<font color="#26A269"><b>    389</b></font> <span style="background-color:#A2734C">    olfactory_check,</span>
<font color="#26A269"><b>    390</b></font> <span style="background-color:#A2734C">    plot_landmarks,</span>
<font color="#26A269"><b>    391</b></font> <span style="background-color:#A2734C">    align_once,</span>
<font color="#26A269"><b>    392</b></font> <span style="background-color:#A2734C">    original_label,</span>
<font color="#26A269"><b>    393</b></font> <span style="background-color:#A2734C">    use_voxelmorph,</span>
<font color="#26A269"><b>    394</b></font> <span style="background-color:#A2734C">    exist_transform,</span>
<font color="#26A269"><b>    395</b></font> <span style="background-color:#A2734C">    voxelmorph_model,</span>
<font color="#26A269"><b>    396</b></font> <span style="background-color:#A2734C">    template_path,</span>
<font color="#26A269"><b>    397</b></font> <span style="background-color:#A2734C">    flow_path,</span>
<font color="#26A269"><b>    398</b></font> <span style="background-color:#A2734C">    coords_input_file,</span>
<font color="#26A269"><b>    399</b></font> <span style="background-color:#A2734C">)</span>

File <font color="#26A269">~/anaconda3/envs/DLC/lib/python3.8/site-packages/mesonet-1.0.5.3-py3.8.egg/mesonet/dlc_predict.py:155</font>, in <font color="#2AA1B3">DLCPredict</font><font color="#12488B">(config, input_file, output, atlas, sensory_match, sensory_path, mat_save, threshold, git_repo_base, region_labels, landmark_arr, use_unet, use_dlc, atlas_to_brain_align, model, olfactory_check, plot_landmarks, align_once, original_label, use_voxelmorph, exist_transform, voxelmorph_model, template_path, flow_path, coords_input_file)</font>
<font color="#26A269"><b>    152</b></font>                 out<font color="#626262">.</font>write(i)
<font color="#26A269"><b>    153</b></font>             out<font color="#626262">.</font>release()
<font color="#26A269">--&gt; 155</font>             <span style="background-color:#A2734C">deeplabcut</span><span style="background-color:#A2734C"><font color="#626262">.</font></span><span style="background-color:#A2734C">analyze_videos(</span>
<font color="#26A269"><b>    156</b></font> <span style="background-color:#A2734C">                config, [video_output_path], videotype</span><span style="background-color:#A2734C"><font color="#626262">=</font></span><span style="background-color:#A2734C"><font color="#AF0000">&quot;.mp4&quot;</font></span><span style="background-color:#A2734C">, save_as_csv</span><span style="background-color:#A2734C"><font color="#626262">=</font></span><span style="background-color:#A2734C"><font color="#008700"><b>True</b></font></span>
<font color="#26A269"><b>    157</b></font> <span style="background-color:#A2734C">            )</span>
<font color="#26A269"><b>    158</b></font>             deeplabcut<font color="#626262">.</font>create_labeled_video(config, [video_name], filtered<font color="#626262">=</font><font color="#008700"><b>True</b></font>)
<font color="#26A269"><b>    159</b></font> <font color="#5F8787"><i>#             if &quot;2.&quot; in deeplabcut.__version__:</i></font>
<font color="#26A269"><b>    160</b></font> <font color="#5F8787"><i>#                 scorer_name = &quot;DeepCut&quot;</i></font>
<font color="#26A269"><b>    161</b></font> <font color="#5F8787"><i>#             else:</i></font>

File <font color="#26A269">~/anaconda3/envs/DLC/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py:487</font>, in <font color="#2AA1B3">analyze_videos</font><font color="#12488B">(config, videos, videotype, shuffle, trainingsetindex, gputouse, save_as_csv, in_random_order, destfolder, batchsize, cropping, TFGPUinference, dynamic, modelprefix, robust_nframes, allow_growth, use_shelve, auto_track, n_tracks, calibrate, identity_only, use_openvino)</font>
<font color="#26A269"><b>    484</b></font> tf<font color="#626262">.</font>compat<font color="#626262">.</font>v1<font color="#626262">.</font>reset_default_graph()
<font color="#26A269"><b>    485</b></font> start_path <font color="#626262">=</font> os<font color="#626262">.</font>getcwd()  <font color="#5F8787"><i># record cwd to return to this directory in the end</i></font>
<font color="#26A269">--&gt; 487</font> cfg <font color="#626262">=</font> <span style="background-color:#A2734C">auxiliaryfunctions</span><span style="background-color:#A2734C"><font color="#626262">.</font></span><span style="background-color:#A2734C">read_config(config)</span>
<font color="#26A269"><b>    488</b></font> trainFraction <font color="#626262">=</font> cfg[<font color="#AF0000">&quot;TrainingFraction&quot;</font>][trainingsetindex]
<font color="#26A269"><b>    489</b></font> iteration <font color="#626262">=</font> cfg[<font color="#AF0000">&quot;iteration&quot;</font>]

File <font color="#26A269">~/anaconda3/envs/DLC/lib/python3.8/site-packages/deeplabcut/utils/auxiliaryfunctions.py:207</font>, in <font color="#2AA1B3">read_config</font><font color="#12488B">(configname)</font>
<font color="#26A269"><b>    204</b></font>                 <font color="#008700"><b>raise</b></font>
<font color="#26A269"><b>    206</b></font> <font color="#008700"><b>else</b></font>:
<font color="#26A269">--&gt; 207</font>     <font color="#008700"><b>raise</b></font> <font color="#D75F5F"><b>FileNotFoundError</b></font>(
<font color="#26A269"><b>    208</b></font>         <font color="#AF0000">&quot;Config file is not found. Please make sure that the file exists and/or that you passed the path of the config file correctly!&quot;</font>
<font color="#26A269"><b>    209</b></font>     )
<font color="#26A269"><b>    210</b></font> <font color="#008700"><b>return</b></font> cfg

<font color="#C01C28">FileNotFoundError</font>: Config file is not found. Please make sure that the file exists and/or that you passed the path of the config file correctly!

</pre>

**Comment by bf777** [comment] 2023-02-21 01:11
Hi @scottkil, thanks for reaching out and for using DeepLabCut! I've determined that this issue was caused by a default config filepath setting for the automated pipelines in the GUI. I've just merged a change that should fix this (#84ebdf2). I've also updated the manual to mention the `get_default_models.sh` script (#14). Let me know if this fixes the issue for you!

**Comment by scottkil** [comment] 2023-02-28 20:57
Looks like it worked. Thanks @bf777. I appreciate the help, and I look forward to using MesoNet!

**Comment by bf777** [comment] 2023-02-28 23:38
I'm glad to hear that it worked @scottkil - happy to help!

**Closed by bf777** 2023-02-28 23:38 UTC
